# Generated by Django 4.1.4 on 2022-12-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_subscribedusers_delete_mailmessage_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscribedusers", name="name",),
    ]
