# Generated by Django 4.1.4 on 2022-12-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_subscribedusers_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("subscription_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(name="SubscribedUsers",),
    ]
