# Generated by Django 4.1.4 on 2022-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_email_newslettersubscriber_sub_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
